language: ruby
rvm:
  - 2.2.2
deploy:
  provider: heroku
  api_key:
    secure: "06160c77051efa37a03b006198930d59dd82097b"  

env:
  - DB=postgresql
script: 
  - RAILS_ENV=development bundle exec rake db:migrate --trace
  
before_script:
 
  - psql -c 'create database my_database_development' -U postgres
bundler_args: --binstubs=./bundler_stubs    